@startuml

title AJAX andd JSON flow example

User -> Website : Page load
activate Website
User -> Website : Request patient modification
Website -> Website: Create modification JSON

Website -> Servlet: <b>[AJAX]</b> Request modify [JSON]
activate Servlet

Servlet -> Servlet: JSON to patient
Servlet -> Controller: Modify patient

activate Controller
Controller --> Servlet: OK
deactivate Controller
Servlet -> Servlet: Result to JSON

Servlet --> Website:<b>[AJAX]</b> OK [JSON]
deactivate Servlet
Website --> Website : Update patient view
Website --> User : Done
deactivate Website

@enduml