@startuml

title Search Example with WhereClauseBuilder

Search --> WhereClauseBuilder : Create<DataModel:Patient>
WhereClauseBuilder --> WhereClauseBuilder : Read Patient fields 

WhereClauseBuilder --> Search : Get possible field names
Search --> Patient : Create search Patient
activate Patient
Search --> WhereClauseBuilder : Search, supply fields names
WhereClauseBuilder --> Patient : Get values
WhereClauseBuilder --> WhereClauseBuilder : Create query 

WhereClauseBuilder --> HybernateDAO : Search patient
activate HybernateDAO
HybernateDAO --> WhereClauseBuilder : Result list of patients
deactivate HybernateDAO

WhereClauseBuilder --> Search : List of patients
Patient --> Search
deactivate Patient
@enduml